import game
MIN_CARDS = 2
MAX_CARDS = 28
HUMAN = 1
CPU = 2

def GetNumOfCards():
    NumOfCards = int(input("Please enter number of cards (bigger than " 
    + str(MIN_CARDS) + ", less than " + str(MAX_CARDS) + ", even number): "))
    if NumOfCards > MIN_CARDS and NumOfCards < MAX_CARDS:
        if NumOfCards % 2 == 0:
            return NumOfCards
    return -1

def DisplayMainMenu():
    choice = int(input("CELEBRITY DOGS\nPlease choose an option: \n1) Play Game \n2) Quit Program \n"))
    return choice
    
    
def PlayGameMain():
    """ this is the main function that gets called by main
    """
    while True:
        choice = DisplayMainMenu()    
        if choice == 2: 
            # do_exit
            exit(-1)
        # currently display menu only has 2 options
        # code below heavily depends on that 
        NumOfCards = GetNumOfCards()
        if NumOfCards != -1:
            break
        print("\nERROR: The number you have entered is invalid\n")
    
    cards = CreateCards.CreCards(NumOfCards)
    list1,list2 = DistributeCards.DisCards(cards)
    
    # start game until one list is empty
    winner = HUMAN    # first hand, make human winner
    while len(list1)!= 0 and len(list2)!= 0:
        if winner == HUMAN:
            show-card (HUMAN card)
            category = input-category()
            show-card (CPU card)
        else:
            show-card (HUMAN card)
            category = randomly generated by CPU
            show-card (CPU card)
            print(category)
        winner,list1,list2 = PlayHand.PlayHand(list1,list2,category)
        if winner == HUMAN or winner == None:
            print("You won the round! Congratulations!")
        else:
            print("Oh No! The CPU has won this round.")
    if len(list1) == 0:
        print("Game over/nThe overall winner is the CPU! Better luck next time!")
    else:
        print("Game over/nYou won the overall game! Congratulations!")
    
        

    


        
